### ISSUE TITLE
box silence is not visible

### ISSUE THREAD

**Issue by abel8909** [RomanSpector/LossOfControl#1]
LossOfControl plugin works perfectly except for one thing the red box is not visible when they cast a silence spell, it only plays audio, it should be noted that I have activated it in the silence panel "it shows the full duration"

**Comment by jonomurphy** [comment]
Experiencing this, too.

**Comment by bijlmermist** [comment]
Hey there. I am experiencing it too for silences, besides that it works like a charm.

may I ask which combatlog fix addon you use exactly? I would like to use and Test it myself.

(Note: I’ve tried it as well with all other addons disabled.)

Thanks for replying in advance!

**Comment by RomanSpector** [comment]
addon combatlogfix: https://disk.yandex.ru/d/2lQuDthAUloohg

If you are all with warmane, then I can tell you that CombatLog works very poorly there. Most likely, the error occurs because of this, so there's nothing I can do, an error on the server side.

**Comment by abel8909** [comment]
> did you have the combatlogfix addon enabled? I didn't find any problems during testing, I need videos or screenshots

I don't know much about lua but I think I have fixed it and it works 

[LOSS_OF_CONTROL_DISPLAY_SILENCE] = LOSS_OF_CONTROL_DISPLAY_SILENCE,

replace

[LOSS_OF_CONTROL_DISPLAY_SILENCE] = LOC_TYPE_SILENCE,

**Comment by bijlmermist** [comment]
> > did you have the combatlogfix addon enabled? I didn't find any problems during testing, I need videos or screenshots
> 
> I do not know much about lua and I do not know if it is correct but I fixed this line and it works
> 
> [LOSS_OF_CONTROL_DISPLAY_SILENCE] = LOSS_OF_CONTROL_DISPLAY_SILENCE,
> 
> replace
> 
> [LOSS_OF_CONTROL_DISPLAY_SILENCE] = LOC_TYPE_SILENCE,

I can confirm that changing the lines makes it work.

**Comment by RomanSpector** [comment]
Yes, that was the mistake. Thank you for finding it!
fix:
https://github.com/RomanSpector/LossOfControl/commit/9fbab4f54c469d3c91b1c4824407df5a1cf14ede
