### ISSUE TITLE
Error (ошибка)

### ISSUE THREAD

**Issue by Vitoshka** [RomanSpector/LossOfControl#2]
Сервер Sirus, словил ошибку

1x LossOfControl-1.0\LossOfControl.lua:81: attempt to call method 'RegisterEvents' (a nil value)
<string>:"safecall Dispatcher[2]":4: in function <[string "safecall Dispatcher[2]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[2]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `SendMessage'
LossOfControl-1.0\LossOfControlOptions.lua:150: in function <...erface\AddOns\LossOfControl\LossOfControlOptions.lua:142>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[1]":9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?:
AceAddon-3.0-12:529: in function `InitializeAddon'
AceAddon-3.0-12:644: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>

  ---

**Comment by RomanSpector** [comment]
Ошибки с Сируса даже не буду рассматривать), тем более что там свой LossOfControl встроенный в клиент
